backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "site/static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: 'products'
    label: 'Products'
    folder: 'site/content/products'
    slug: "{{slug}}"
    create: true
    fields:
      - {label: "Name", name: "title", widget: "string" }
      - {label: "SKU", name: "sku", widget: "string" }
      - {label: "Price", name: "price", widget: "number"}
      - {label: "Image", name: "image", widget: "string"}
      - {label: "Body", name: "body", widget: "string"}  
      - {label: "Slug", name: "slug", widget: "string" }

  - label: "Settings"
    name: "Settings"
    delete: false
    editor:
      preview: false
    files:
      - name: "delivery_days"
        label: "Delivery Days"
        file: "site/data/delivery_days.json"
        description: "Choose available delivery and pickup days"
        fields:
          - {label: "Sundays", name: "sundays", widget: "boolean", required: false}
          - {label: "Mondays", name: "mondays", widget: "boolean", required: false}
          - {label: "Tuesdays", name: "tuesdays", widget: "boolean", required: false}
          - {label: "Wednesdays", name: "wednesdays", widget: "boolean", required: false}
          - {label: "Thursdays", name: "thursdays", widget: "boolean", required: false}
          - {label: "Fridays", name: "fridays", widget: "boolean", required: false}
          - {label: "Saturdays", name: "saturdays", widget: "boolean", required: false}
      - name: "date_settings"
        label: "Date Settings"
        file: "site/data/date_settings.json"
        description: "Set blackout dates"
        fields:
          - label: "Blackout Dates"
            name: "blackout_dates"
            widget: "list"
            fields:
              - {label: "Start Date", name: "start_date", widget: "date", default: ""}
              - {label: "End Date", name: "end_date", widget: "date", default: ""}

