backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "site/static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: 'products'
    label: 'Products'
    folder: 'site/content/products'
    slug: "{{slug}}"
    create: true
    fields:
      - {label: "Name", name: "title", widget: "string" }
      - {label: "SKU", name: "sku", widget: "string" }
      - {label: "Price", name: "price", widget: "number"}
      - {label: "Image", name: "image", widget: "string"}
      - {label: "Body", name: "body", widget: "string"}  
      - {label: "Slug", name: "slug", widget: "string" }

  - label: "Settings"
    name: "Settings"
    delete: false
    editor:
      preview: false
    files:
      - name: "shipping"
        label: "Shipping Settings"
        file: "site/data/settings.json"
        description: "Settings for delivery and pickup days"
        fields:
          - {label: "Deliver Sundays", name: "deliver_sundays", widget: "boolean", required: false}
          - {label: "Deliver Mondays", name: "deliver_mondays", widget: "boolean", required: false}
          - {label: "Deliver Tuesdays", name: "deliver_tuesdays", widget: "boolean", required: false}
          - {label: "Deliver Wednesdays", name: "deliver_wednesdays", widget: "boolean", required: false}
          - {label: "Deliver Thursdays", name: "deliver_thursdays", widget: "boolean", required: false}
          - {label: "Deliver Fridays", name: "deliver_fridays", widget: "boolean", required: false}
          - {label: "Deliver Saturdays", name: "deliver_saturdays", widget: "boolean", required: false}
